#!/usr/bin/env node
import path from "node:path";
import {
  buildWorkerGeneratedEnv,
  loadContract,
  pullVercelEnv,
  repoRoot,
  writeEnvFile,
} from "./lib.mjs";

function parseEnvironmentArg(argv) {
  const idx = argv.indexOf("--environment");
  if (idx >= 0 && argv[idx + 1]) {
    return argv[idx + 1];
  }
  return "development";
}

function parseOutputArg(argv) {
  const idx = argv.indexOf("--output");
  if (idx >= 0 && argv[idx + 1]) {
    return path.resolve(argv[idx + 1]);
  }
  return path.join(repoRoot, "worker", ".env.generated");
}

function main() {
  const argv = process.argv.slice(2);
  const environment = parseEnvironmentArg(argv);
  const outputPath = parseOutputArg(argv);

  const contract = loadContract();
  const pulledEnv = pullVercelEnv(environment);
  const { env, sourceByKey, missingRequired } = buildWorkerGeneratedEnv(contract, pulledEnv);

  if (missingRequired.length > 0) {
    console.error("[env-sync] Missing required worker keys after Vercel pull:");
    for (const key of missingRequired) {
      console.error(`- ${key}`);
    }
    process.exit(1);
  }

  const orderedKeys = [
    ...new Set([
      ...contract.worker.required_local,
      ...contract.vercel_pull_keys_for_worker,
      ...Object.keys(contract.worker.local_defaults),
    ]),
  ];

  writeEnvFile(
    outputPath,
    env,
    orderedKeys,
    [
      "Generated by scripts/env/sync_worker_from_vercel.mjs",
      `Environment source: vercel (${environment})`,
      "Do not commit this file.",
    ],
  );

  console.log(`[env-sync] Wrote ${outputPath}`);
  for (const key of orderedKeys) {
    if (env[key]) {
      console.log(`[env-sync] ${key}: set (${sourceByKey[key] ?? "unknown"})`);
    }
  }
}

main();
