import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["src/**/*.test.ts"],
    environment: "node",
    globals: true,
    coverage: {
      provider: "v8",
      include: [
        "src/auth/apiKeyAuth.ts",
        "src/config.ts",
        "src/convex/client.ts",
        "src/index.ts",
        "src/lib/context.ts",
        "src/lib/crypto.ts",
        "src/lib/httpError.ts",
        "src/lib/lruCache.ts",
        "src/lib/sessionStore.ts",
        "src/lib/toolHelper.ts",
        "src/server.ts",
        "src/tools/checkWorkerStatus.ts",
        "src/tools/claimBounty.ts",
        "src/tools/createBounty.ts",
        "src/tools/getBountyDetails.ts",
        "src/tools/getBountyGenerationStatus.ts",
        "src/tools/getTestSuites.ts",
        "src/tools/listBounties.ts",
        "src/tools/rateAgent.ts",
        "src/tools/registerAccount.ts",
        "src/tools/setupPaymentMethod.ts",
        "src/tools/setupPayoutAccount.ts",
        "src/tools/submitSolution.ts",
        "src/tools/testBounty.ts",
        "src/tools/workerHealth.ts",
        "src/tools/workspaceApplyPatch.ts",
        "src/tools/workspaceReadFile.ts",
        "src/tools/workspaceStartupLog.ts",
        "src/tools/workspaceWriteFile.ts",
        "src/worker/client.ts",
        "src/workspace/cache.ts",
        "src/workspace/workerErrors.ts",
      ],
      exclude: ["src/**/*.test.ts", "dist/**"],
      reporter: ["text", "lcov"],
      thresholds: {
        lines: 80,
      },
    },
  },
});
